# *************************************************
#   2024 : Arthur JEULIN
#   Copyright (c) Coast Autonomous
#   Created by Arthur JEULIN on 10/09/2024
#**************************************************
#
# Module : Dockerfile with RTMaps install
#

FROM ubuntu:22.04

ENTRYPOINT [ "bash" ]